/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestão.de.stock.pkgfinal;

import java.awt.Color;

/**
 *
 * @author PAT
 */
public class GestãoDeStockFINAL extends javax.swing.JFrame {

     Color preto = new Color(0,0,0);; 
     Color branco = new Color(232, 236, 244);
     boolean clickCon;
     boolean clickImp;
     boolean clickArm;
     boolean clickCen;
    
    /**
     * Creates new form Main
     */
    public GestãoDeStockFINAL() {
        initComponents();
        setResizable(false);
       
       Main main = new Main();
       paginas.add(main).setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        logoMainn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelConsumivel = new javax.swing.JPanel();
        btnConsumivel = new javax.swing.JLabel();
        painelImpressora = new javax.swing.JPanel();
        btnImpressora = new javax.swing.JLabel();
        painelArmazem = new javax.swing.JPanel();
        btnArmazem = new javax.swing.JLabel();
        painelCentroCusto = new javax.swing.JPanel();
        btnCentroCusto = new javax.swing.JLabel();
        paginas = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(232, 236, 244));
        mainPanel.setPreferredSize(new java.awt.Dimension(1070, 650));

        menuPanel.setBackground(new java.awt.Color(0, 0, 0));
        menuPanel.setPreferredSize(new java.awt.Dimension(1070, 40));

        logoMainn.setFont(new java.awt.Font("Webdings", 0, 11)); // NOI18N
        logoMainn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pikaaaa-svg.png"))); // NOI18N
        logoMainn.setText("jLabel1");
        logoMainn.setMaximumSize(new java.awt.Dimension(220, 40));
        logoMainn.setMinimumSize(new java.awt.Dimension(220, 327));
        logoMainn.setPreferredSize(new java.awt.Dimension(220, 40));
        logoMainn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMainnMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONSUMÍVEIS");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 40));

        painelConsumivel.setBackground(new java.awt.Color(0, 0, 0));
        painelConsumivel.setPreferredSize(new java.awt.Dimension(120, 40));
        painelConsumivel.setLayout(new java.awt.BorderLayout());

        btnConsumivel.setBackground(new java.awt.Color(0, 0, 0));
        btnConsumivel.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnConsumivel.setForeground(new java.awt.Color(255, 255, 255));
        btnConsumivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsumivel.setText("CONSUMíVEIS");
        btnConsumivel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsumivel.setPreferredSize(new java.awt.Dimension(100, 20));
        btnConsumivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsumivelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsumivelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsumivelMouseExited(evt);
            }
        });
        painelConsumivel.add(btnConsumivel, java.awt.BorderLayout.CENTER);

        painelImpressora.setBackground(new java.awt.Color(0, 0, 0));
        painelImpressora.setPreferredSize(new java.awt.Dimension(120, 40));
        painelImpressora.setLayout(new java.awt.BorderLayout());

        btnImpressora.setBackground(new java.awt.Color(0, 0, 0));
        btnImpressora.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnImpressora.setForeground(new java.awt.Color(255, 255, 255));
        btnImpressora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnImpressora.setText("IMPRESSORAS");
        btnImpressora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImpressora.setPreferredSize(new java.awt.Dimension(100, 20));
        btnImpressora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImpressoraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImpressoraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImpressoraMouseExited(evt);
            }
        });
        painelImpressora.add(btnImpressora, java.awt.BorderLayout.CENTER);

        painelArmazem.setBackground(new java.awt.Color(0, 0, 0));
        painelArmazem.setPreferredSize(new java.awt.Dimension(120, 40));
        painelArmazem.setLayout(new java.awt.BorderLayout());

        btnArmazem.setBackground(new java.awt.Color(0, 0, 0));
        btnArmazem.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnArmazem.setForeground(new java.awt.Color(255, 255, 255));
        btnArmazem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnArmazem.setText("ARMAZÉNS");
        btnArmazem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArmazem.setPreferredSize(new java.awt.Dimension(100, 20));
        btnArmazem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArmazemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArmazemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArmazemMouseExited(evt);
            }
        });
        painelArmazem.add(btnArmazem, java.awt.BorderLayout.CENTER);

        painelCentroCusto.setBackground(new java.awt.Color(0, 0, 0));
        painelCentroCusto.setPreferredSize(new java.awt.Dimension(160, 40));
        painelCentroCusto.setLayout(new java.awt.BorderLayout());

        btnCentroCusto.setBackground(new java.awt.Color(0, 0, 0));
        btnCentroCusto.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnCentroCusto.setForeground(new java.awt.Color(255, 255, 255));
        btnCentroCusto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCentroCusto.setText("CENTRO DE CUSTO");
        btnCentroCusto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCentroCusto.setPreferredSize(new java.awt.Dimension(100, 20));
        btnCentroCusto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCentroCustoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCentroCustoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCentroCustoMouseExited(evt);
            }
        });
        painelCentroCusto.add(btnCentroCusto, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(logoMainn, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(painelConsumivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(painelImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelCentroCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoMainn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelConsumivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCentroCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        paginas.setBackground(new java.awt.Color(232, 236, 244));

        javax.swing.GroupLayout paginasLayout = new javax.swing.GroupLayout(paginas);
        paginas.setLayout(paginasLayout);
        paginasLayout.setHorizontalGroup(
            paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paginasLayout.setVerticalGroup(
            paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paginas)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(paginas))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsumivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsumivelMouseClicked
        // TODO add your handling code here:
        
        //Definir cores 
        clickCon = true;
        clickImp = false;
        clickCen = false;
        clickArm = false;
        
        painelConsumivel.setBackground(branco);
            btnConsumivel.setForeground(preto);
            
            painelImpressora.setBackground(preto);
            painelCentroCusto.setBackground(preto);
            painelArmazem.setBackground(preto);
            
            btnImpressora.setForeground(branco);
            btnArmazem.setForeground(branco);
            btnCentroCusto.setForeground(branco);
        
    }//GEN-LAST:event_btnConsumivelMouseClicked
 
    private void btnImpressoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImpressoraMouseClicked
        // TODO add your handling code here:
        //Definir cores 
        
        clickImp = true;
        clickCon = false;
        clickCen = false;
        clickArm = false;
        
         painelImpressora.setBackground(branco);
            btnImpressora.setForeground(preto);
            
            painelConsumivel.setBackground(preto);
            painelCentroCusto.setBackground(preto);
            painelArmazem.setBackground(preto);
            
            btnConsumivel.setForeground(branco);
            btnArmazem.setForeground(branco);
            btnCentroCusto.setForeground(branco);
    }//GEN-LAST:event_btnImpressoraMouseClicked

    private void btnConsumivelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsumivelMouseEntered
        // TODO add your handling code here:
        
         painelConsumivel.setBackground(branco);
            btnConsumivel.setForeground(preto);
    }//GEN-LAST:event_btnConsumivelMouseEntered

    private void btnImpressoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImpressoraMouseEntered
        // TODO add your handling code here:
        
        painelImpressora.setBackground(branco);
            btnImpressora.setForeground(preto);
    }//GEN-LAST:event_btnImpressoraMouseEntered

    private void btnConsumivelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsumivelMouseExited
        // TODO add your handling code here:
        if(!clickCon)
        {
            painelConsumivel.setBackground(preto);
            btnConsumivel.setForeground(branco);
        }
         
    }//GEN-LAST:event_btnConsumivelMouseExited

    private void btnImpressoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImpressoraMouseExited
        // TODO add your handling code here:
        if(!clickImp)
        {
            painelImpressora.setBackground(preto);
            btnImpressora.setForeground(branco);
        }
         
    }//GEN-LAST:event_btnImpressoraMouseExited

    private void btnArmazemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArmazemMouseClicked
        // TODO add your handling code here:
        clickCen = false;
        clickArm = true;
        clickImp = false;
        clickCon = false;
        
        painelArmazem.setBackground(branco);
            btnArmazem.setForeground(preto);
            
            painelImpressora.setBackground(preto);
            painelCentroCusto.setBackground(preto);
            painelConsumivel.setBackground(preto);
            
            btnImpressora.setForeground(branco);
            btnConsumivel.setForeground(branco);
            btnCentroCusto.setForeground(branco);
    }//GEN-LAST:event_btnArmazemMouseClicked

    private void btnArmazemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArmazemMouseEntered
        // TODO add your handling code here:
        
        painelArmazem.setBackground(branco);
            btnArmazem.setForeground(preto);
    }//GEN-LAST:event_btnArmazemMouseEntered

    private void btnArmazemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArmazemMouseExited
        // TODO add your handling code here:
        if(!clickArm)
        {
            painelArmazem.setBackground(preto);
            btnArmazem.setForeground(branco);
        }
        
    }//GEN-LAST:event_btnArmazemMouseExited

    private void btnCentroCustoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroCustoMouseClicked
        // TODO add your handling code here:
        clickCen = true;
        clickArm = false;
        clickImp = false;
        clickCon = false;
        
         painelCentroCusto.setBackground(branco);
            btnCentroCusto.setForeground(preto);
            
            painelConsumivel.setBackground(preto);
            painelImpressora.setBackground(preto);
            painelArmazem.setBackground(preto);
            
            btnConsumivel.setForeground(branco);
            btnArmazem.setForeground(branco);
            btnImpressora.setForeground(branco);
    }//GEN-LAST:event_btnCentroCustoMouseClicked

    private void btnCentroCustoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroCustoMouseEntered
        // TODO add your handling code here:
        painelCentroCusto.setBackground(branco);
            btnCentroCusto.setForeground(preto);
    }//GEN-LAST:event_btnCentroCustoMouseEntered

    private void btnCentroCustoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroCustoMouseExited
        // TODO add your handling code here:
        if(!clickCen)
        {
             painelCentroCusto.setBackground(preto);
            btnCentroCusto.setForeground(branco);
        }
    }//GEN-LAST:event_btnCentroCustoMouseExited

    private void logoMainnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMainnMouseClicked
        // TODO add your handling code here:
        
         clickCen = false;
        clickArm = false;
        clickImp = false;
        clickCon = false;
        
         painelCentroCusto.setBackground(preto);
            btnCentroCusto.setForeground(branco);
            
            painelConsumivel.setBackground(preto);
            painelImpressora.setBackground(preto);
            painelArmazem.setBackground(preto);
            
            btnConsumivel.setForeground(branco);
            btnArmazem.setForeground(branco);
            btnImpressora.setForeground(branco);
            
            ////////////////////////////////////////////////////////////
            
            //Remover a pagina antiga
        paginas.removeAll();
        //Criar objeto para nova class
        Main hm = new Main();
        //Adicionar a nova página
        paginas.add(hm).setVisible(true);
    }//GEN-LAST:event_logoMainnMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestãoDeStockFINAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestãoDeStockFINAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestãoDeStockFINAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestãoDeStockFINAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestãoDeStockFINAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnArmazem;
    private javax.swing.JLabel btnCentroCusto;
    private javax.swing.JLabel btnConsumivel;
    private javax.swing.JLabel btnImpressora;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoMainn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JDesktopPane paginas;
    private javax.swing.JPanel painelArmazem;
    private javax.swing.JPanel painelCentroCusto;
    private javax.swing.JPanel painelConsumivel;
    private javax.swing.JPanel painelImpressora;
    // End of variables declaration//GEN-END:variables
}
